name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.30.0
        with:
          php-version: '8.3'
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install gettext
        run: sudo apt-get install gettext

      - name: Build translations
        run: for file in `find . -name "*.po"` ; do msgfmt -o ${file/.po/.mo} $file ; done

      - name: Build
        run: pnpm build
